apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t109ib35c-python
  janus-idp.io/tekton: t109ib35c-python
  backstage.io/kubernetes-id: t109ib35c-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t109ib35c-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
